[psql]
  dbname = "stakewatcher"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  schema = "public"
  sslmode= "disable"
  blacklist = ["migrations"]

[[aliases.tables]]
name = "block_signatures"
  [[aliases.tables.relationships]]
  name    = "block_signatures_validators_validator_address_fkey"
  foreign = "Validator"

[[aliases.tables]]
name = "blocks"
  [[aliases.tables.relationships]]
  name    = "blocks_validators_proposer_address_fkey"
  foreign = "Proposer"

[[aliases.tables]]
name = "transactions"
  [[aliases.tables.relationships]]
  name    = "transactions_blocks_height_fkey"
  foreign = "Block"
